/*
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

import std.datetime.stopwatch;
import Dmemmove: Dmemmove;
import S_struct;
import std.random;
import std.stdio;
import core.stdc.string;
import std.traits;

void main(string[] args)
{
    // For performing benchmarks
    stdout.flush();
    testStatic!(byte);
    testStatic!(ubyte);
    testStatic!(short);
    testStatic!(ushort);
    testStatic!(int);
    testStatic!(uint);
    testStatic!(long);
    testStatic!(ulong);
    testStatic!(float);
    testStatic!(double);
    testStatic!(real);
    testStatic!(S!1);
    testStatic!(S!3);
    testStatic!(S!7);
    testStatic!(S!13);
    testStatic!(S!22);
    testStatic!(S!29);
    testStatic!(S!39);
    testStatic!(S!45);
    testStatic!(S!54);
    testStatic!(S!63);
    testStatic!(S!64);
    static foreach(i; 120..130)
    {
        testStatic!(S!i);
    }
    static foreach(i; 220..230)
    {
        testStatic!(S!i);
    }
    static foreach(i; 720..730)
    {
        testStatic!(S!i);
    }
    testStatic!(S!3452);
    testStatic!(S!6598);
    testStatic!(S!14928);
    testStatic!(S!27891);
    testStatic!(S!44032);
    testStatic!(S!55897);
    testStatic!(S!79394);

    testStatic!(S!256);
    testStatic!(S!512);
    testStatic!(S!1024);
    testStatic!(S!2048);
    testStatic!(S!4096);
    testStatic!(S!8192);
    testStatic!(S!16384);
    testStatic!(S!32768);
    testStatic!(S!65536);
}

// From a very good Chandler Carruth video on benchmarking: https://www.youtube.com/watch?v=nXaxk27zwlk
void escape(void* p)
{
    version(LDC)
    {
        import ldc.llvmasm;
         __asm("", "r,~{memory}", p);
    }
    version(GNU)
    {
        asm { "" : : "g" p : "memory"; }
    }
}

void Cmemmove(T)(T *dst, const T *src)
{
    import core.stdc.string: memmove;
    pragma(inline, true)
    memmove(dst, src, T.sizeof);
}

void Cmemmove(T)(T[] dst, const T[] src)
{
    import core.stdc.string: memmove;
    assert(dst.length == src.length);
    pragma(inline, true)
    memmove(dst.ptr, src.ptr, dst.length * T.sizeof);
}

void Cmemcpy(T)(T *dst, const T *src)
{
    import core.stdc.string: memcpy;
    pragma(inline, true)
    memcpy(dst, src, T.sizeof);
}

void Cmemcpy(T)(T[] dst, const T[] src)
{
    import core.stdc.string: memcpy;
    assert(dst.length == src.length);
    pragma(inline, true)
    memcpy(dst.ptr, src.ptr, dst.length * T.sizeof);
}

void init(T)(T *v)
{
    static if (is(T == float))
    {
        *v = uniform(0.0f, 9_999_999.0f);
    }
    else static if (is(T == double))
    {
        *v = uniform(0.0, 9_999_999.0);
    }
    else static if (is(T == real))
    {
        *v = uniform(0.0L, 9_999_999.0L);
    }
    else
    {
        auto m = (cast(ubyte*)v)[0 .. T.sizeof];
        for(int i = 0; i < m.length; i++)
        {
            m[i] = uniform!byte;
        }
    }
}

void verify(T)(const T *a, const T *b)
{
    const ubyte *aa = (cast(const ubyte*)a);
    const ubyte *bb = (cast(const ubyte*)b);
    for(size_t i = 0; i < T.sizeof; i++)
    {
        assert(aa[i] == bb[i]);
    }
}

void testStatic(T)()
{
    T d, s;
    init(&d);
    init(&s);
    Dmemmove(&d, &s);
    verify(&d, &s);
}

void init(T)(ref T[] v)
{
    static if (is (T == float))
    {
        v = uniform(0.0f, 9_999_999.0f);
    }
    else static if (is(T == double))
    {
        v = uniform(0.0, 9_999_999.0);
    }
    else static if (is(T == real))
    {
        v = uniform(0.0L, 9_999_999.0L);
    }
    else
    {
        for(int i = 0; i < v.length; i++)
        {
            v[i] = uniform!byte;
        }
    }
}

void verify(T)(const ref T[] a, const ref T[] b)
{
    assert(a.length == b.length);
    for(int i = 0; i < a.length; i++)
    {
        assert(a[i] == b[i]);
    }
}

/*
void testDynamic(size_t n)
{
    ubyte[80000] buf1;
    ubyte[80000] buf2;

    // TODO(stefanos): This should be a static foreach
    for (int j = 0; j < 3; ++j) {
        double TotalGBperSec1 = 0.0;
        double TotalGBperSec2 = 0.0;
        enum alignments = 32;

        foreach(i; 0..alignments)
        {
            ubyte[] p = buf1[i..i+n];
            ubyte[] q = buf2[i..i+n];

            // Relatively aligned
            if (j == 0)
            {
                q = buf2[i..i+n];
            }
            else {
                // src forward
                if (j == 1)
                {
                    q = buf1[n/2..n/2+n];
                // dst forward
                }
                else
                {
                    q = p;
                    p = buf1[n/2..n/2+n];
                }
            }

            ulong bytesCopied1;
            ulong bytesCopied2;
            init(q);
            init(p);
            immutable d1 = benchmark!(ubyte, Cmemmove)(p, q, &bytesCopied1);
            verify(q, p);

            init(q);
            init(p);
            immutable d2 = benchmark!(ubyte, Dmemmove)(p, q, &bytesCopied2);
            verify(q, p);

            auto secs1 = (cast(double)(d1.total!"nsecs")) / 1_000_000_000.0;
            auto secs2 = (cast(double)(d2.total!"nsecs")) / 1_000_000_000.0;
            auto GB1 = (cast(double)bytesCopied1) / 1_000_000_000.0;
            auto GB2 = (cast(double)bytesCopied2) / 1_000_000_000.0;
            auto GBperSec1 = GB1 / secs1;
            auto GBperSec2 = GB2 / secs2;
            if (average)
            {
                TotalGBperSec1 += GBperSec1;
                TotalGBperSec2 += GBperSec2;
            }
            else
            {
                writeln(n, " ", GBperSec1, " ", GBperSec2);
                stdout.flush();
            }
        }

        if (average)
        {
            write(n, " ", TotalGBperSec1 / alignments, " ", TotalGBperSec2 / alignments);
            if (j == 0) {
                writeln(" - Relatively aligned");
            } else if (j == 1) {
                writeln(" - src forward");
            } else {
                writeln(" - dst forward");
            }
            stdout.flush();
        }
    }
}
*/
